# Generated by Django 5.2.4 on 2025-08-06 03:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_passwordresettoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(default='nice', max_length=128),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='otp',
            name='username',
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='purpose',
            field=models.CharField(default='register', max_length=30),
        ),
    ]
